### PR TITLE
Spirv fixes

### PR DESCRIPTION
**Pull request by pvelesko**
Can't edit your fork so opened this one. Please review & close the other PR.

### CODE REVIEW

**Comment by linehill** [comment]
Using `hipcc` from the install location fails on my machine:

```
$ HIPCC_VERBOSE=7 __HIP_PLATFORM_SPIRV__=1 ../install/bin/hipcc hello.hip -o hello-hip
Searching for .hipInfo in /mnt/md1/linehill/chip-spv-space/install/bin/../share
Hip Clang Compiler not found
HIP_PATH=/mnt/md1/linehill/chip-spv-space/install
HIP_PLATFORM=intel
HIP_COMPILER=clang
HIP_RUNTIME=spirv
HIP_CLANG_PATH=/mnt/md1/linehill/chip-spv-space/install/bin
HIP_CLANG_INCLUDE_PATH=/mnt/md1/linehill/chip-spv-space/install/lib/clang/include
HIP_INCLUDE_PATH=/mnt/md1/linehill/chip-spv-space/install/include
HIP_LIB_PATH=
DEVICE_LIB_PATH=
hipcc-args: hello.hip -o hello-hip 
hipcc-cmd: /mnt/md1/linehill/chip-spv-space/install/bin/clang++ -L/mnt/md1/linehill/chip-spv-space/install/lib -lCHIP -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -lOpenCL -lze_loader -Wl,-rpath,/mnt/md1/linehill/chip-spv-space/install/lib  hello.hip -o hello-hip
clang-14: error: cannot find ROCm device library; provide its path via '--rocm-path' or '--rocm-device-lib-path', or pass '-nogpulib' to build without ROCm device library

failed to execute:/mnt/md1/linehill/chip-spv-space/install/bin/clang++ -L/mnt/md1/linehill/chip-spv-space/install/lib -lCHIP -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -lOpenCL -lze_loader -Wl,-rpath,/mnt/md1/linehill/chip-spv-space/install/lib  hello.hip -o hello-hip
```

**Comment by pvelesko** [comment]
1. No need for `__HIP_PLATFORM_SPIRV__=1`
2. Your install seems messed up. Can you paste the .hipInfo here? 

```
HIP_CLANG_PATH=/mnt/md1/linehill/chip-spv-space/install/bin
HIP_CLANG_INCLUDE_PATH=/mnt/md1/linehill/chip-spv-space/install/lib/clang/include
```

Is your clang really installed in `/mnt/md1/linehill/chip-spv-space/install/bin`? Can you verify that `llvm-config` is there?

**Comment by linehill** [comment]
llvm-config:
```
$ ../install/bin/llvm-config --version
14.0.6
```

Clang:
```
$ ../install/bin/clang++ --version
clang version 14.0.6 (https://github.com/llvm/llvm-project.git f28c006a5895fc0e329fe15fead81e37457cb1d1)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /mnt/md1/linehill/chip-spv-space/sandbox/../install/bin
```

.hipInfo:
```
$ cat ../install/share/.hipInfo 
# Auto-generated by cmake on 2022-10-31T11:30:07Z UTC
HIP_PATH=/mnt/md1/linehill/chip-spv-space/install
HIP_RUNTIME=spirv
HIP_COMPILER=clang
HIP_ARCH=spirv
HIP_CLANG_PATH=/mnt/md1/linehill/chip-spv-space/install/bin
HIP_OFFLOAD_COMPILE_OPTIONS=-D__HIP_PLATFORM_SPIRV__= -x hip --target=x86_64-linux-gnu --offload=spirv64 -nohipwrapperinc --hip-path=/mnt/md1/linehill/chip-spv-space/install
HIP_OFFLOAD_LINK_OPTIONS=-L/mnt/md1/linehill/chip-spv-space/install/lib -lCHIP -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -lOpenCL -lze_loader -Wl,-rpath,/mnt/md1/linehill/chip-spv-space/install/lib
```

**Comment by pvelesko** [comment]
Can you run through a debugger and let me know where it fails? Function of interest:

```
string HipBinSpirv::getCompilerVersion() {
  string out, complierVersion;
  const string &hipClangPath = getCompilerPath();
  fs::path cmd = hipClangPath;
  /**
   * Ubuntu systems do not provide this symlink clang++ -> clang++-14
   * Maybe use llvm-config instead?
   * $: llvm-config --version
   * $: 14.0.0
   */
  cmd /= "/llvm-config";
  if (canRunCompiler(cmd.string(), out) || canRunCompiler("llvm-config", out)) {
    regex regexp("([0-9.]+)");
    smatch m;
    if (regex_search(out, m, regexp)) {
      if (m.size() > 1) {
        // get the index =1 match, 0=whole match we ignore
        std::ssub_match sub_match = m[1];
        complierVersion = sub_match.str();
      }
    }
  } else {
    cout << "Hip Clang Compiler not found" << endl;
  }
  return complierVersion;
}
```

**Comment by linehill** [comment]
* `HipBinSpirv::getCompilerVersion()`: The `cmd` string evaluates to `/llvm-config`. There is a missing prefix?
* `HipBinBase::canRunCompiler()`: `tmpFileName` evaluates to empty string creating invalid commands (e.g. `llvm-config --version >  2>&1`). This error is introduced by 991239217eaff3be9e5f3dd8a5cf8f301ba63d51 where `mktemp()` is replaced with `mkstemp()`. The latter one does not return a string and modifies the argument instead (https://linux.die.net/man/3/mkstemp).

**Comment by pvelesko** [comment]
> The cmd string evaluates to /llvm-config. There is a missing prefix?

That's the first issue - this should be the `HIP_CLANG_PATH` from `.hipInfo` can you verify that `.hipInfo` got parsed correctly? 

> This error is introduced by https://github.com/CHIP-SPV/HIPCC/commit/991239217eaff3be9e5f3dd8a5cf8f301ba63d51 where mktemp()

the only difference between mktemp and mkstemp is that mkstemp creates the file whereas mktemp does not. Not sure what error you are referring to.

**Comment by linehill** [comment]
> ...verify that .hipInfo got parsed correctly?
This is what `readHipInfo()` parses:
```
*** HipInfo::runtime='spirv'
*** HipInfo::cxxflags='-D__HIP_PLATFORM_SPIRV__= -x hip --target=x86_64-linux-gnu --offload=spirv64 -nohipwrapperinc --hip-path=/mnt/md1/linehill/chip-spv-space/install'
*** HipInfo::ldflags='-L/mnt/md1/linehill/chip-spv-space/install/lib -lCHIP -L/usr/lib/x86_64-linux-gnu -L/usr/lib/x86_64-linux-gnu -lOpenCL -lze_loader -Wl,-rpath,/mnt/md1/linehill/chip-spv-space/install/lib'
*** HipInfo::clangpath='/mnt/md1/linehill/chip-spv-space/install/bin'
```
> Not sure what error you are referring to.

```
  fileName = mkstemp(&name[0]);
```
`mkstemp()` returns a file descriptor or an error (`int`) - not a `string` - and it is assigned to std::string. The result is a character - possibly non-visible.

**Comment by pvelesko** [comment]
> mkstemp() returns a file descriptor or an error (int) - not a string - and it is assigned to std::string. The result is a character - possibly non-visible.

Well that part was copied from AMD and I only changed mktemp -> mkstemp the only difference being creating a file. 

Your .hipInfo looks correct. I'm not sure what is going on and I have no way of debugging without being able to reproduce the error.

**Comment by pvelesko** [comment]
The issue is that you named your file .hip. Is this common? I haven't seen any other examples using this extension. If .hip is used, should we assume that it's a C++ program? @linehill

**Comment by pvelesko** [comment]
@linehill pull & check please

**Comment by linehill** [comment]
LGTM. IMHO, It would be great if the HIPCC didn't output noise in non-verbose invocations:

```
$ ../install/bin/hipcc hello.hip -o hello-hip
Searching for .hipInfo in /mnt/md1/linehill/ws-chip-spv-2/install/bin/../share
Hip Clang Compiler not found
```

> The issue is that you named your file .hip. Is this common? I haven't seen any other examples using this extension. If .hip is used, should we assume that it's a C++ program?

Clang and HIPCC on AMD platform (see `hipBin_amd.h`) recognizes `.hip` suffix as HIP source (aka. C++ with HIP language extensions). LLVM and PyTorch has `.hip` suffixed files.

Regarding the previous review comments: It seems now that the issues I brought up were wrong. It’s probable I had an incorrect branch checked out for the review - so sorry about that.

**Review by linehill — APPROVED** [review]

**Comment by pvelesko** [comment]
> It would be great if the HIPCC didn't output noise in non-verbose invocations:

I agree but for now I will leave it just to make sure that .hipInfo is found since HIPCC for CHIP-SPV is not 100% complete and probably never will be as AMD is moving towards getting rid of it.

**Pull request merged**
